### ISSUE TITLE
Adjustment for net migration

### ISSUE THREAD

**Issue by NFitzhenry** [timriffe/AdultCoverage#7]
Hi Tim,

Thank you so much for developing this tool.

I was wondering if it were possible to make an adjustment for net migration before estimating completeness? 

Thanks,
Nick

**Comment by timriffe** [comment]
Hi Nick,
I was working on that in the fury of 2020 and recall it being implemented in the GitHub version of the package but not on CRAN. Just include a column `mig` in your input data object, and note the column `mig.summed` (logical) to specify whether the net migration given is summed (`TRUE`) or averaged (`FALSE`). If I remember correctly, the three methods support this, as does the wrapper `ddm()`, but I think I left the interactive visual adjustment function in a broken state. There are also other features, including easier-to-interpret output, and more line fitting methods. That's probably why I didn't push to CRAN. I don't know when will be the next time I maintain this package. You can install from here using `remotes::install_github("timriffe/AdultCoverage/AdultCoverage/R/DDM")`. Please report back if this doesn't satisfy the request so that we can make this issue more specific.

**Comment by NFitzhenry** [comment]
Thanks Tim! Really excited to hear that you have implemented this. 

Unortunately the installation line is not working. It seems to be downloading all of your other packages. Might this be what is making it fail? 

![image](https://user-images.githubusercontent.com/131788272/235123403-c3cfe883-1a3d-4d76-b0ff-2101748394f7.png)

**Comment by timriffe** [comment]
I see,

try this:

remotes::install_github("mpascariu/MortalityLaws")

then:

remotes::install_github("mpascariu/MortalityEtimate")

then

remotes::install_github("timriffe/DemoTools")

then try DDM again. If DemoTools installation gives more flak then ping
back here. The other day it was necessary to run install.packages("rstan")
first, which on my machine took ~30 minutes to install.

**Comment by NFitzhenry** [comment]
Your suggestion worked! Thanks Tim! 

I have about 200 sensitivity analyses to run and I was not looking forward to implmenting them using the http://demographicestimation.iussp.org/content/synthetic-extinct-generations-methods spreadsheets. 

Lets see if I can get this done before the supervisor meeting. Really appreciate your work.

I will let you know if I am able to implement the mig adjustment.

**Comment by timriffe** [comment]
OK, great, now let's hope DDM works as expected for you!

**Comment by NFitzhenry** [comment]
Worked just fine! Thanks Tim

For your interest, here are my results. I need to see if I can refine my age-migration data. The original age groups were in fifteen year intervals that i divided equally into 5 year bins. But will work on that later. 

![image](https://user-images.githubusercontent.com/131788272/235173157-76b6bdc7-e731-4129-ba63-fd305df3b880.png)

![image](https://user-images.githubusercontent.com/131788272/235173100-97dd4a83-2f24-443a-9e3f-442fac086cf6.png)
