### ISSUE TITLE
intercept in regression

### ISSUE THREAD

**Issue by IvanWilli** [timriffe/AdultCoverage#8]
Hi! thanks for the package! really nice. Working with this right now.
I think `slopeint` calculation of intercept is not ok. Today is:
`
intercept <- with(codi, mean(leftterm[age %in% agesfit]) * 
        (1/slope) - mean(rightterm[age %in% agesfit]))
`
And probably should be:
`
intercept <- with(codi, mean(leftterm[age %in% agesfit]) - 
         slope * mean(rightterm[age %in% agesfit]))
`
This is because $a=\mu_y-b*\mu_x$.
The effect is not big because small numbers in regression, and because coverage is calculated with slope, not intercept.
Iván

**Comment by timriffe** [comment]
Indeed, it looks like <https://github.com/timriffe/AdultCoverage/issues/3> needed to be found in more places.

**Comment by timriffe** [comment]
eps Ivan, see <https://github.com/timriffe/AdultCoverage/blob/master/AdultCoverage/R/DDM/R/plot_functions.R> line 247. The fix was made in 2020. Are you seeing this elsewhere too? I see the CRAN version <https://cran.r-project.org/web/packages/DDM/index.html> is still 2017. Many improvements and fixes were made back in 2020, so please use the github version, and let me know of feedback. I don't recall the reasons I didn't push to CRAN then nor if it'd be an easy push or not now, so let me know if that should be on fast-forward.

**Comment by IvanWilli** [comment]
Oh! my bad! Sorry. 
Not necesary from my side to update to CRAN.
Thanks man.
Closing this
